---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
namespace: monitoring
metadata:
  name: yarn
  labels:
      app: yarn
spec:
  selector:
    matchLabels:
      app: yarn
  endpoints:
  - port: metrics 
