---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: prometheus
    labels:
        prometheus: prometheus
spec:
    replicas: 3
    serviceAccountName: prometheus
    serviceMonitorSelector:
        matchLabels:
            app: yarn
