version: '3'

services:
  resourcemanager:
    image: babbleshack/hadoop:3-2-1-federation
    container_name: resourcemanager
    restart: unless-stopped
    hostname: hadoop-master
    command: "/bin/sleep infinity"
    deploy:
      placement:
        constraints:
          - "node.labels.role==master"
  
  nodemanager:
    image: babbleshack/hadoop:3-2-1-federation
    restart: unless-stopped
    command: "/bin/sleep infinity"
    deploy:
      placement:
        constraints:
          - "node.labels.role==master"

  namenode:
    image: babbleshack/hadoop:3-2-1
    restart: unless-stopped
    command: "/bin/sleep infinity"
    deploy:
      replicas: 3
      placement:
        constraints:
          - "node.labels.role==worker"

  datanode:
    image: babbleshack/hadoop:3-2-1
    restart: unless-stopped
    command: "/bin/sleep infinity"
    deploy:
      replicas: 3
      placement:
        constraints:
          - "node.labels.role==worker"

  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.labels.role==master"

#networks:
#  hostnet:
#    external: true
#    name: host
