version: '3'

services:
  resourcemanager:
    image: babbleshack/hadoop:3-2-1-federation
    container_name: resourcemanager
    restart: unless-stopped
    hostname: hadoop-master
    command: "/bin/sleep infinity"
  
  nodemanager:
    image: babbleshack/hadoop:3-2-1-federation
    restart: unless-stopped
    command: "/bin/sleep infinity"
    deploy:
      replicas: 3

  namenode:
    image: babbleshack/hadoop:3-2-1
    restart: unless-stopped
    command: "/bin/sleep infinity"
    deploy:
      replicas: 3

  datanode:
    image: babbleshack/hadoop:3-2-1
    restart: unless-stopped
    command: "/bin/sleep infinity"
    deploy:
      replicas: 3

  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    restart: unless-stopped


