---
#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: yarn-subcluster-a
---
#######
#SERVICE
########
kind: Service
apiVersion: v1
metadata:
  name: yarn-service
  namespace: yarn-subcluster-a
  labels:
    app: yarn
    yarn: master
spec:
  selector:
    app: yarn
  ports: #Hadoop port http://fibrevillage.com/storage/637-hadoop-default-ports-reference
    - name: rm-web
      protocol: TCP
      port: 8088
    - name: router-web
      protocol: TCP
      port: 8089
    - name: tl-web
      protocol: TCP
      port: 8188
    - name: mr-web
      protocol: TCP
      port: 19888
    - name: nodemanager
      protocol: TCP
      port: 7777
    - name: nm-webapp
      protocol: TCP
      port: 8042
---
kind: Service
apiVersion: v1
metadata:
  name: yarn-master-service
  namespace: yarn-subcluster-a
  labels:
    app: yarn
    yarn: master
spec:
  selector:
    yarn: master
  ports: #Hadoop port http://fibrevillage.com/storage/637-hadoop-default-ports-reference
    - name: rm-web
      protocol: TCP
      port: 8088
    - name: router-web
      protocol: TCP
      port: 8089
    - name: rm-rev-proxy
      protocol: TCP
      port: 8010
    - name: tl-web
      protocol: TCP
      port: 8188
    - name: mr-job-his
      protocol: TCP
      port: 10020
    - name: mr-web
      protocol: TCP
      port: 19888
    - name: spark-history
      protocol: TCP
      port: 18080
    - name: spark-web-ui
      protocol: TCP
      port: 4040
    - name: proxy
      protocol: TCP
      port: 7071

---
##############
#STATEFUL-SET
##############
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-master
  namespace: yarn-subcluster-a
  labels:
    app: yarn
    yarn: master
spec:
  serviceName: yarn-service
  replicas: 1 
  selector:
    matchLabels:
      yarn: master
  template: #pod template .spec.template
    metadata:
      namespace: yarn-subcluster-a
      labels:
        app: yarn
        yarn: master
        monitor: hadoop
    spec:
      hostname: yarn-master-0.yarn-service
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - yarn
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: master
      containers:
        - name: yarn-master
          image: babbleshack/hadoop:3-2-1-federated
          imagePullPolicy: Always
          command: [ "/bin/bash" ]
          args: [ "/hadoop/scripts/startRM.sh" ]
          volumeMounts: 
            - name: workers
              mountPath: /workers
          env:
            - name: CLUSTER_ID
              value: yarn-subcluster-a
            - name: ROUTER
              value: "true"
          ports:
          - name: rm-web
            containerPort: 8088
          - name: router-web
            containerPort: 8089
          - name: rm-rev-proxy
            containerPort: 8010
          - name: tl-web
            containerPort: 8188
          - name: spark-history
            containerPort: 18080
          - name: mr-job-his
            containerPort: 10020
          - name: mr-web
            containerPort: 19888
          - name: spark-web-ui
            containerPort: 4040
          - name: proxy
            containerPort: 7071
        - name: hadoop-exporter
          image: babbleshack/hadoop:hadoop_exporter
          imagePullPolicy: Always
          ports:
          - name: metrics
            containerPort: 8000
      volumes:
        - name: workers
          configMap:
            name: workers
---
# stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-worker
  namespace: yarn-subcluster-a
  labels:
    app: yarn
    yarn: worker
spec:
  serviceName: yarn-service
  replicas: 10
  selector:
    matchLabels:
      yarn: worker
  template:
    metadata:
      namespace: yarn-subcluster-a
      labels:
        app: yarn
        yarn: worker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: worker
                  operator: In
                  values:
                  - yarn
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: worker
      containers:
        - name: yarn-worker
          image: babbleshack/hadoop:3-2-1-federated
          imagePullPolicy: Always
          command: [ "/bin/bash" ]
          args: [ "/hadoop/scripts/startNM.sh" ]
          env:
            - name: CLUSTER_ID
              value: yarn-subcluster-a
            - name: PASSIVE_MODE
              value: "true"
          ports:
          - name: rm-web
            containerPort: 8088
          - name: router-web
            containerPort: 8089
          - name: tl-web
            containerPort: 8188
          - name: mr-web
            containerPort: 19888
          - name: nodemanager
            containerPort: 7777
          - name: nm-webapp
            containerPort: 8042
