---
#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: yarn-subcluster-b
---
kind: Service
apiVersion: v1
metadata:
  name: yarn-service
  namespace: yarn-subcluster-b
  labels:
    app: yarn
    yarn: master
spec:
  selector:
    app: yarn
  ports: #Hadoop port http://fibrevillage.com/storage/637-hadoop-default-ports-reference
    - name: rm-sched
      protocol: TCP
      port: 8030
    - name: rt
      protocol: TCP
      port: 8031
    - name: rm
      protocol: TCP
      port: 8032
    - name: rm-admin
      protocol: TCP
      port: 8033
    - name: nm
      protocol: TCP
      port: 8040
    - name: nm-2
      protocol: TCP
      port: 8042
    - name: amrmproxy
      protocol: TCP
      port: 8049
    - name: rm-admin-http
      protocol: TCP
      port: 8088
    - name: tl-server
      protocol: TCP
      port: 8188
    - name: job-his-rpc
      protocol: TCP
      port: 10020
    - name: job-his
      protocol: TCP
      port: 10033
    - name: job-his-ui
      protocol: TCP
      port: 19888
    - name: sp-port
      protocol: TCP
      port: 13562
---
kind: Service
apiVersion: v1
metadata:
  name: yarn-master-service
  namespace: yarn-subcluster-b
  labels:
    app: yarn
    yarn: master
spec:
  selector:
    yarn: master
  ports: #Hadoop port http://fibrevillage.com/storage/637-hadoop-default-ports-reference
    - name: rm-sched
      protocol: TCP
      port: 8030
    - name: rt
      protocol: TCP
      port: 8031
    - name: rm
      protocol: TCP
      port: 8032
    - name: rm-admin
      protocol: TCP
      port: 8033
    - name: nm
      protocol: TCP
      port: 8040
    - name: nm-2
      protocol: TCP
      port: 8042
    - name: rm-admin-http
      protocol: TCP
      port: 8088
    - name: job-his-rpc
      protocol: TCP
      port: 10020
    - name: job-his
      protocol: TCP
      port: 10033
    - name: nm-3
      protocol: TCP
      port: 13562
    - name: job-his-ui
      protocol: TCP
      port: 19888
    - name: amrmproxy
      protocol: TCP
      port: 8049
    - name: tl-server
      protocol: TCP
      port: 8188
    - name: router-clientrm
      protocol: TCP
      port: 8050
    - name: router-webapp
      protocol: TCP
      port: 8089
    - name: router-admin
      protocol: TCP
      port: 8052
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-master
  namespace: yarn-subcluster-b
  labels:
    app: yarn
    yarn: master
spec:
  serviceName: yarn-service
  replicas: 1 
  selector:
    matchLabels:
      yarn: master
  template: #pod template .spec.template
    metadata:
      namespace: yarn-subcluster-b
      labels:
        app: yarn
        yarn: master
    spec:
      hostname: yarn-master-0.yarn-service
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - yarn
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: master
      containers:
        - name: yarn-master
          image: babbleshack/hadoop:3-2-1-federation
          imagePullPolicy: Always
          command: [ "/bin/bash" ]
          args: [ "/hadoop/scripts/startRM.sh" ]
          volumeMounts: 
            - name: workers
              mountPath: /workers
          env:
            - name: CLUSTER_ID
              value: yarn-subcluster-b
          ports:
            - name: rm-sched
              containerPort: 8030
            - name: rt
              containerPort: 8031
            - name: rm
              containerPort: 8032
            - name: rm-admin
              containerPort: 8033
            - name: rmam-proxy
              containerPort: 8049
            - name: rm-admin-http
              containerPort: 8088
            - name: job-his-rpc
              containerPort: 10020
            - name: job-his
              containerPort: 10033
            - name: job-his-ui
              containerPort: 19888
            - name: webapp
              containerPort: 8088
            - name: timeline-serv
              containerPort: 8188
            - name: timeline-rpc
              containerPort: 10200
            - name: router-clientrm
              containerPort: 8050
            - name: router-webapp
              containerPort: 8089
            - name: router-admin
              containerPort: 8052
      volumes:
        - name: workers
          configMap:
            name: workers
---
# stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-worker
  namespace: yarn-subcluster-b
  labels:
    app: yarn
    yarn: worker
spec:
  serviceName: yarn-service
  replicas: 10
  selector:
    matchLabels:
      yarn: worker
  template:
    metadata:
      namespace: yarn-subcluster-b
      labels:
        app: yarn
        yarn: worker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: worker
                  operator: In
                  values:
                  - yarn
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: worker
      containers:
        - name: yarn-worker
          image: babbleshack/hadoop:3-2-1-federation
          imagePullPolicy: Always
          command: [ "/bin/bash" ]
          args: [ "/hadoop/scripts/startNM.sh" ]
          env:
            - name: CLUSTER_ID
              value: yarn-subcluster-b
            - name: PASSIVE_MODE
              value: "true"
          ports:
            - name: rm-sched
              containerPort: 8030
            - name: rt
              containerPort: 8031
            - name: rm
              containerPort: 8032
            - name: rm-admin
              containerPort: 8033
            - name: amrmproxy
              containerPort: 8049
            - name: nm
              containerPort: 8040
            - name: nm-2
              containerPort: 8042
            - name: job-his-rpc
              containerPort: 10020
            - name: job-his
              containerPort: 10033
            - name: nm-3
              containerPort: 13562
            - name: ssh
              containerPort: 22
            - name: timeline-serv
              containerPort: 8188
            - name: timeline-rpc
              containerPort: 10200


